const styles = {
    container: {
        padding: "30px",
        fontFamily: "Inter, sans-serif",
    },
    title: {
        color: "#2f0d51",
        fontSize: "2rem",
        marginBottom: "10px",
    },
    subtitle: {
        color: "#666",
        fontSize: "1.1rem",
        marginBottom: "30px",
    },
    abas: {
        display: "flex",
        gap: "10px",
        marginBottom: "25px",
    },
    aba: {
        padding: "12px 25px",
        backgroundColor: "#f8f9fa",
        border: "1px solid #dee2e6",
        borderRadius: "8px",
        cursor: "pointer",
        fontSize: "1rem",
        transition: "all 0.3s ease",
    },
    abaAtiva: {
        backgroundColor: "#2f0d51",
        color: "white",
        borderColor: "#2f0d51",
    },
    card: {
        backgroundColor: "white",
        padding: "25px",
        borderRadius: "12px",
        boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
        border: "1px solid #e9ecef",
        marginBottom: "25px",
    },
    cardTitle: {
        fontSize: "1.3rem",
        color: "#495057",
        marginBottom: "20px",
        fontWeight: "600",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
    },
    iaBadge: {
        backgroundColor: "#6f42c1",
        color: "white",
        padding: "4px 8px",
        borderRadius: "12px",
        fontSize: "0.7rem",
        fontWeight: "600",
    },
    badge: {
        backgroundColor: "#ffc107",
        color: "#333",
        padding: "4px 8px",
        borderRadius: "12px",
        fontSize: "0.8rem",
        fontWeight: "600",
    },
    formGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
        gap: "20px",
        marginBottom: "25px",
    },
    formGroup: {
        marginBottom: "15px",
    },
    label: {
        display: "block",
        marginBottom: "8px",
        fontWeight: "600",
        color: "#333",
    },
    iaHint: {
        fontSize: "0.8rem",
        color: "#6f42c1",
        fontWeight: "normal",
    },
    input: {
        width: "100%",
        padding: "10px 12px",
        border: "2px solid #e9ecef",
        borderRadius: "6px",
        fontSize: "1rem",
        boxSizing: "border-box",
    },
    sugestoesIA: {
        marginTop: "10px",
        padding: "15px",
        backgroundColor: "#f8f9fa",
        borderRadius: "8px",
        border: "1px solid #e3f2fd",
    },
    sugestoesTitulo: {
        margin: "0 0 10px 0",
        fontSize: "0.9rem",
        fontWeight: "600",
        color: "#6f42c1",
    },
    sugestoesLista: {
        display: "flex",
        gap: "8px",
        flexWrap: "wrap",
    },
    sugestaoButton: {
        padding: "8px 12px",
        border: "none",
        borderRadius: "6px",
        fontSize: "0.8rem",
        cursor: "pointer",
        transition: "all 0.3s ease",
        display: "flex",
        alignItems: "center",
        gap: "5px",
    },
    primaryButton: {
        backgroundColor: "#28a745",
        color: "white",
        border: "none",
        padding: "12px 25px",
        borderRadius: "8px",
        fontSize: "1rem",
        fontWeight: "600",
        cursor: "pointer",
    },
    secondaryButton: {
        backgroundColor: "#6c757d",
        color: "white",
        border: "none",
        padding: "10px 15px",
        borderRadius: "6px",
        fontSize: "0.9rem",
        cursor: "pointer",
    },
    importacao: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
        gap: "20px",
    },
    importacaoItem: {
        padding: "20px",
        backgroundColor: "#f8f9fa",
        borderRadius: "8px",
        border: "1px solid #dee2e6",
    },
    fileInput: {
        width: "100%",
        margin: "10px 0",
    },
    tableContainer: {
        overflowX: "auto",
    },
    table: {
        width: "100%",
        borderCollapse: "collapse",
    },
    th: {
        backgroundColor: "#eaf2ff",
        padding: "12px 15px",
        textAlign: "left",
        fontWeight: "600",
        color: "#2f0d51",
        borderBottom: "2px solid #2f0d51",
    },
    td: {
        padding: "12px 15px",
        borderBottom: "1px solid #eee",
        verticalAlign: "top",
    },
    sku: {
        color: "#666",
        fontSize: "0.8rem",
    },
    status: {
        padding: "4px 8px",
        borderRadius: "12px",
        fontSize: "0.7rem",
        fontWeight: "600",
    },
    smallButton: {
        backgroundColor: "#bb25a6",
        color: "white",
        border: "none",
        padding: "6px 10px",
        borderRadius: "4px",
        fontSize: "0.8rem",
        cursor: "pointer",
        marginRight: "5px",
    },
    smallButtonDanger: {
        backgroundColor: "#dc3545",
        color: "white",
        border: "none",
        padding: "6px 10px",
        borderRadius: "4px",
        fontSize: "0.8rem",
        cursor: "pointer",
    },
    modalOverlay: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0, 0, 0, 0.5)",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1000,
    },
    modalContent: {
        backgroundColor: "white",
        padding: "30px",
        borderRadius: "12px",
        boxShadow: "0 5px 15px rgba(0, 0, 0, 0.3)",
        width: "90%",
        maxWidth: "500px",
    },
    modalTitle: {
        fontSize: "1.5rem",
        color: "#2f0d51",
        marginBottom: "20px",
    },
    modalActions: {
        marginTop: "30px",
        display: "flex",
        justifyContent: "flex-end",
        gap: "10px",
    },
    cancelButton: {
        backgroundColor: "#6c757d",
        color: "white",
        border: "none",
        padding: "10px 20px",
        borderRadius: "8px",
        cursor: "pointer",
        fontWeight: "600",
    },
    saveButton: {
        backgroundColor: "#28a745",
        color: "white",
        border: "none",
        padding: "10px 20px",
        borderRadius: "8px",
        cursor: "pointer",
        fontWeight: "600",
    },
    loading: {
        textAlign: "center",
        padding: "50px",
        color: "#666",
    },
};

export default styles;
